use super::{
    MAX_ACCESSES_PER_TEST, MAX_CONCRETE_TESTS, MAX_GRANULE_BYTES, MAX_IDENTIFIER_UTF8_BYTES,
    MAX_QUERY_ADDRESSES, MAX_RAW_INPUT_BYTES, MAX_REPORT_BYTES, MAX_REPORT_TARGET_ROWS,
    MAX_REPORT_WINDOW_ROWS, MAX_STREAMS_PER_CASE, MAX_TARGET_COUNT, MAX_TOTAL_GENERATED_ACCESSES,
    MAX_WINDOW_SIZES_PER_CASE, MAX_WINDOW_WORK, MAX_YAML_SCALAR_UTF8_BYTES,
};

#[test]
fn v1_limits_match_the_normative_operational_table() {
    // Given / When / Then
    assert_eq!(MAX_RAW_INPUT_BYTES, 16 * 1024 * 1024);
    assert_eq!(MAX_YAML_SCALAR_UTF8_BYTES, 128);
    assert_eq!(MAX_QUERY_ADDRESSES, 1_000_000);
    assert_eq!(MAX_TARGET_COUNT, 65_536);
    assert_eq!(MAX_GRANULE_BYTES, 1_u128 << 52);
    assert_eq!(MAX_ACCESSES_PER_TEST, 10_000_000);
    assert_eq!(MAX_CONCRETE_TESTS, 10_000);
    assert_eq!(MAX_TOTAL_GENERATED_ACCESSES, 100_000_000);
    assert_eq!(MAX_STREAMS_PER_CASE, 4_096);
    assert_eq!(MAX_WINDOW_SIZES_PER_CASE, 1_024);
    assert_eq!(MAX_IDENTIFIER_UTF8_BYTES, 128);
    assert_eq!(MAX_REPORT_TARGET_ROWS, 1_000_000);
    assert_eq!(MAX_REPORT_WINDOW_ROWS, 1_000_000);
    assert_eq!(MAX_WINDOW_WORK, 100_000_000);
    assert_eq!(MAX_REPORT_BYTES, 268_435_456);
}
